tasks:
  - name: aws-sam
    init: |
      cd /workspace
      wget https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip
      unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
      sudo ./sam-installation/install
      cd $THEIA_WORKSPACE_ROOT
  - name: cfn
    before: |
      bundle update --bundler
      pip install cfn-lint
      cargo install cfn-guard
      gem install cfn-toml
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: full
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
    command: |
      bash "$THEIA_WORKSPACE_ROOT/bin/init-envars"
      echo "export WORKSAPCE_ROOT_PATH='$THEIA_WORKSPACE_ROOT'" >> ~/.envar
      echo "export WORKSPACE_NAME_ID='$GITPOD_WORKSPACE_ID'" >> ~/.envar
      echo "export WORKSPACE_HOST_PORT='$GITPOD_WORKSPACE_CLUSTER_HOST'" >> ~/.envar
      export WORKSPACE_IP=$(curl ifconfig.me)
      bash "$THEIA_WORKSPACE_ROOT/bin/bootstrap"
  
  - name: postgres
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
      

  - name: react-js
    command: |
      cd frontend-react-js
      npm i

  - name: flask
    command: |
      cd backend-flask
      pip install -r requirements.txt

  - name: fargate
    before: |
      cd /workspace
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      cd $THEIA_WORKSPACE_ROOT/backend-flask

  - name: cdk
    before: |
      npm install aws-cdk -g
      cd thumbing-serverless-cdk
      cp .env.example .env
      npm i

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - cweijan.vscode-postgresql-client2
    # - gp validate
    - ms-vscode.Theme-PredawnKit

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
